### ISSUE TITLE
Please support Magisk 17.3

### ISSUE THREAD

**Issue by ubergeek77** [LawnchairLauncher/LawnstepModule#1]
I have a Google Pixel 3 XL with Magisk 17.3. This is the only version of Magisk that currently supports the Pixel 3 phones.

When trying to install the module, the installer quits and tells me "Please install Magisk v17.2+!"

Since I can't actually install anything lower than 17.3 on my Pixel 3 XL, it is impossible for me to not have satisfied this requirement, and yet I still can't install the module.

**Comment by skittles9823** [comment]
@ubergeek77 The module installs on the 17.4 snapshot for me (basically identical to the 17.3 beta except with debugging enabled in the build). Could you send /data/adb/magisk/util_functions.sh so I can try to see why it isn't working.

**Comment by skittles9823** [comment]
@ubergeek77 The module installs on the 17.4 snapshot for me (basically identical to the 17.3 beta except with debugging enabled in the build). Could you send /data/adb/magisk/util_functions.sh so I can try to see why it isn't working.

**Comment by ubergeek77** [comment]
I can't find this issue page anymore, I'm getting a 404 not found when
loading it, and the issues page on this repository is empty. I'm going to
try replying to this via email, hopefully you see it.

I can send you util_functions.sh if you really need it, but I think I've
already identified the problem. At the very top, MAGISK_VER_CODE is set to
17100, and MAGISK_VER is set to 17.1. This is really confusing, since I was
forced to do a factory reset to install Magisk, so I couldn't have any old
configurations or anything of the sort on my Pixel 3. Not to mention it is
impossible for me to have 17.1, since it's a Pixel, and anything lower than
17.3 will fail to install. Maybe topjohnwu forgot to change this in all of
the Pixel 3 excitement?

But this means it's not actually your module that was the problem, but
Magisk. I was still able to install Lawnstep by manually changing minMagisk
to 17100 in module.prop, then everything works as expected. I'll try
manually changing these values in util_functions to avoid this in the
future. Thanks for making me aware of that!

**Comment by skittles9823** [comment]
@ubergeek77 hmm real interesting. I'll let John know about this now.

**Comment by skittles9823** [comment]
@ubergeek77 Did you flash a pre patched boot image? If so, next time try to do the install through magisk manager with setting the update channel to beta so it grabs the updated until_functilns.sh

**Comment by ubergeek77** [comment]
Since this is a Google Pixel 3XL, and I was doing the initial root, I had
to generate a patched image using Magisk, and then flash it via fastboot. I
was following these instructions:

https://www.xda-developers.com/google-pixel-3-unlock-bootloader-root-magisk/

I saw on his Twitter that he pulled 17.3 from stable and can't fix the
issues with it until he completes school work, and he directed people who
own Pixel 3 XL devices to use the canary channel. Maybe that has something
to do with the version mismatch.

In any case, I've updated to the Canary channel and allowed Magisk to flash
the boot image itself, and the variables in util_functions.sh are now sane.
But something from the above XDA instructions caught my eye. Take a look at:

6. Tap “Install” again, though you won’t be installing the zip file that it’s showing you.

Indeed, when I went through these instructions, it was *showing* me 17.1,
but it really generated a boot image for 17.3, which I then installed via
fastboot to initially root my 3XL. It's possible Magisk picked up
MAGISK_VER variables from this, and set them as 17.1, even though Magisk
17.3 was installed. It even showed as 17.3 correctly in the Magisk Manager
app.

If this is where the source of the issue is (and it probably is, a friend's phone was rooted this way, and his util_functions variables were also messed up), please be prepared for an influx of people who catch wind of this module, who think they have 17.3 and can't install Lawnstep!

**Comment by ubergeek77** [comment]
By the way, does Lawnstep not yet support the Lens feature on the Recents screen? On stock Pie, you can use OCR to select text or select an image. I used that feature a lot, it doesn't seem to be working on LawnStep.

**Comment by skittles9823** [comment]
@ubergeek77 yea that feature won't work unless we find a way to whitelist lawnchair in Action Services. We are working on it and hope to find a way to get that working.

**Comment by skittles9823** [comment]
On that note, I'll close this issue now since you have everything working :)

**Comment by ubergeek77** [comment]
Thanks for the info! I'm glad it wasn't an issue with your module, and
hopefully topjohnwu will be back soon with a stable Magisk release so this
doesn't happen to anyone else!
