### ISSUE TITLE
Quickstep does not appear to work with Magisk 18.2

### ISSUE THREAD

**Issue by viggy96** [LawnchairLauncher/LawnstepModule#3]
Hello, I am using Magisk canary 18.2-0204d053, as it is the only version to properly pass SafetyNet consistently at the moment, and Quickstep does not appear to work. Also, I am using LOS 16.0/Pie. 

I am running Lawnchair v2-alpha-914 from APKMirror. Quickstep does not switch the recents app from the default Trebuchet on my device. I can't even change it to com.android.systemui. Note, I reboot after changing the settings, as said by the app.

**Comment by suphon-t** [comment]
Please give more information. Do you have Magisk core only mode enabled?

**Comment by skittles9823** [comment]
As Paphon said, make sure core only mode is off. Also can you grab the logs from /sdcard/documents/quickstepswitcher

I can confirm it's not related to Magisk 18.2 as I've been running the debug canary builds for months and not had an issue myself.

**Comment by viggy96** [comment]
Nevermind, it appeared to be a bug with LineageOS. With an update to it, everything was working as it should.
